apiVersion: apps/v1
kind: Deployment
metadata:
  name: progtexts2
  labels:
    app: progtexts2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progtexts2
  template:
    metadata:
      labels:
        app: progtexts2
        app.kubernetes.io/name: progtexts2
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
              name: prog-nginx-svc
          volumeMounts:
            - name: config-vol
              mountPath: "/etc/nginx/conf.d"
        - image: zharaskhan/progtexts2-master
          imagePullPolicy: "Always"
          name: progtexts2
          ports:
            - containerPort: 8000
          resources: {}
      volumes:
      - name: config-vol
        configMap:
          name: nginx-config
          items:
            - key: nginx.conf
              path: nginx.conf
      restartPolicy: Always
