apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: progtexts2
  name: progtexts2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progtexts2
  template:
    metadata:
      labels:
        app: progtexts2
    spec:
      containers:
        - image: zharaskhan/progtexts2-master
          name: progtexts2
          ports:
            - containerPort: 80
      restartPolicy: Always