apiVersion: v1
kind: Service
metadata:
  name: progtexts2
spec:
  selector:
    app.kubernetes.io/name: progtexts2
  ports:
  - name: http
    protocol: TCP
    port: 31743
    targetPort: progtexts2-svc
  type: LoadBalancer
