apiVersion: v1
kind: Service
metadata:
  name: progtexts2
spec:
  selector:
    app.kubernetes.io/name: progtexts2
  ports:
  - name: http
    protocol: TCP
    port: 31743
    targetPort: prog-nginx-svc
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: progtexts2-nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - notes.cpfed.kz
    secretName: progtexts2-tls-secret-random-string-for-security
  rules:
  - host: notes.cpfed.kz
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: progtexts2
              port:
                number: 31743